/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import models.Controlador;
import models.users.Cliente;

/**
 *
 * @author sabela
 */
public class Registro extends javax.swing.JDialog {
    
    private Controlador controller;

    /**
     * Creates new form Registro
     */
    public Registro(java.awt.Frame parent, boolean modal, Controlador controller) {
        super(parent, modal);
        this.controller=controller;
        faltanCamposCliente.setVisible(false);
        faltanCamposEmpresa.setVisible(false);
        falloEmpresaRegistrada.setVisible(false);
        falloEmailRegistrado.setVisible(false);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        aceptarBtnCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoNombreCliente = new javax.swing.JTextField();
        textoEmailCliente = new javax.swing.JTextField();
        textoPasswordCliente = new javax.swing.JTextField();
        textoDirCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        falloEmailRegistrado = new javax.swing.JLabel();
        faltanCamposCliente = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        textoTlfCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textoIbanCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textoNombreEmpresa = new javax.swing.JTextField();
        textoNIF = new javax.swing.JTextField();
        textoEmailEmpresa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textoIBANempresa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textoTlfEmpresa = new javax.swing.JTextField();
        textoPasswordEmpresa = new javax.swing.JTextField();
        textoDirEmpresa = new javax.swing.JTextField();
        aceptarBtnEmpresa = new javax.swing.JButton();
        cancelarBtnEmpresa = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        falloEmpresaRegistrada = new javax.swing.JLabel();
        faltanCamposEmpresa = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        aceptarBtnCliente.setText("Aceptar");
        aceptarBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("NUEVO USUARIO");

        jLabel2.setText("Nombre");

        jLabel3.setText("E-mail");

        jLabel4.setText("Contraseña");

        jLabel5.setText("DIreccion");

        textoEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEmailClienteActionPerformed(evt);
            }
        });

        textoDirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDirClienteActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        falloEmailRegistrado.setForeground(new java.awt.Color(245, 26, 26));
        falloEmailRegistrado.setText("E-mail registrado");

        faltanCamposCliente.setForeground(new java.awt.Color(213, 50, 50));
        faltanCamposCliente.setText("Falta algún campo");

        jLabel6.setText("Telefono");

        textoTlfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTlfClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Iban");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(textoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 187, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(faltanCamposCliente)
                                    .addComponent(falloEmailRegistrado))))
                        .addContainerGap(152, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aceptarBtnCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(48, 48, 48)
                                    .addComponent(textoEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoTlfCliente)
                                        .addComponent(textoPasswordCliente)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textoDirCliente)
                                        .addComponent(textoIbanCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(falloEmailRegistrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(faltanCamposCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPasswordCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textoTlfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textoIbanCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textoDirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtnCliente)
                    .addComponent(jButton1))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("CLIENTE", jPanel1);

        jLabel8.setText("Nombre");

        jLabel9.setText("NIF");

        jLabel10.setText("e-mail");

        jLabel11.setText("NUEVA EMPRESA");

        textoNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreEmpresaActionPerformed(evt);
            }
        });

        textoEmailEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEmailEmpresaActionPerformed(evt);
            }
        });

        jLabel12.setText("IBAN");

        jLabel13.setText("telefono");

        textoTlfEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTlfEmpresaActionPerformed(evt);
            }
        });

        textoPasswordEmpresa.setText("jTextField1");

        textoDirEmpresa.setText("jTextField2");
        textoDirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDirEmpresaActionPerformed(evt);
            }
        });

        aceptarBtnEmpresa.setText("Aceptar");
        aceptarBtnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnEmpresaActionPerformed(evt);
            }
        });

        cancelarBtnEmpresa.setText("Cancela");
        cancelarBtnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnEmpresaActionPerformed(evt);
            }
        });

        jLabel14.setText("password");

        jLabel15.setText("direccion");

        falloEmpresaRegistrada.setText("Esta empresa ya está registrada");

        faltanCamposEmpresa.setText("Faltan campos por completar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(aceptarBtnEmpresa)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarBtnEmpresa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(199, 199, 199)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(falloEmpresaRegistrada)
                            .addComponent(faltanCamposEmpresa)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoPasswordEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(textoNombreEmpresa)
                            .addComponent(textoNIF)
                            .addComponent(textoEmailEmpresa)
                            .addComponent(textoIBANempresa)
                            .addComponent(textoTlfEmpresa)
                            .addComponent(textoDirEmpresa))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(falloEmpresaRegistrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(faltanCamposEmpresa)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textoNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textoNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textoEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPasswordEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(textoIBANempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTlfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtnEmpresa)
                    .addComponent(cancelarBtnEmpresa))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EMPRESA", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textoDirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDirClienteActionPerformed

    private void textoEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEmailClienteActionPerformed

    private void aceptarBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnClienteActionPerformed
        // TODO add your handling code here:
        falloEmailRegistrado.setVisible(false);
        faltanCamposCliente.setVisible(false);
        Cliente user = new Cliente(textoTlfCliente.getText(), textoIbanCliente.getText(), null, 
                textoNombreCliente.getText(), textoEmailCliente.getText(), textoPasswordCliente.getText(), 
                textoDirCliente.getText()); 
        
        if (textoNombreCliente.getText().isEmpty() || textoIbanCliente.getText().isEmpty() || textoTlfCliente.getText().isEmpty()
                || textoEmailCliente.getText().isEmpty() || textoPasswordCliente.getText().isEmpty() || textoDirCliente.getText().isEmpty()) {
            faltanCamposCliente.setVisible(true);
        } else if (controller.existeUsuario(user)) {
            falloEmailRegistrado.setVisible(true);
        } else {
            controller.registrarUsuario(user);

        }
    }//GEN-LAST:event_aceptarBtnClienteActionPerformed

    private void textoNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreEmpresaActionPerformed

    private void textoTlfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTlfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTlfClienteActionPerformed

    private void textoEmailEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEmailEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEmailEmpresaActionPerformed

    private void textoTlfEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTlfEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTlfEmpresaActionPerformed

    private void aceptarBtnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarBtnEmpresaActionPerformed

    private void cancelarBtnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBtnEmpresaActionPerformed

    private void textoDirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDirEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDirEmpresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtnCliente;
    private javax.swing.JButton aceptarBtnEmpresa;
    private javax.swing.JButton cancelarBtnEmpresa;
    private javax.swing.JLabel falloEmailRegistrado;
    private javax.swing.JLabel falloEmpresaRegistrada;
    private javax.swing.JLabel faltanCamposCliente;
    private javax.swing.JLabel faltanCamposEmpresa;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField textoDirCliente;
    private javax.swing.JTextField textoDirEmpresa;
    private javax.swing.JTextField textoEmailCliente;
    private javax.swing.JTextField textoEmailEmpresa;
    private javax.swing.JTextField textoIBANempresa;
    private javax.swing.JTextField textoIbanCliente;
    private javax.swing.JTextField textoNIF;
    private javax.swing.JTextField textoNombreCliente;
    private javax.swing.JTextField textoNombreEmpresa;
    private javax.swing.JTextField textoPasswordCliente;
    private javax.swing.JTextField textoPasswordEmpresa;
    private javax.swing.JTextField textoTlfCliente;
    private javax.swing.JTextField textoTlfEmpresa;
    // End of variables declaration//GEN-END:variables
}
